{
 "title": "Traffic (ClickHouse)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "srcip",
    "label": "Filter by Source IP",
    "query": "select sip from (\nselect IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))) as sip, time_flow_start_ns from flows_raw where etype = 0x800 group by sip, time_flow_start_ns order by time_flow_start_ns DESC limit 1 by sip limit 10)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Instant traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT\n    t,\n    sum(sumbytes) AS sumbytes\nFROM (\n    SELECT\n        $timeSeries AS t,\n        sum(bytes*sampling_rate) as sumbytes\n    FROM $table\n    WHERE $timeFilter\n    GROUP BY t\n\n    UNION ALL\n\n    SELECT\n        intDiv($from+number*$interval, $interval)*$interval*1000 AS t,\n        0 AS sumbytes\n    FROM numbers(intDiv($to-$from, $interval))\n)\nGROUP BY t\nORDER BY t",
     "query": "SELECT\n    t,\n    sum(sumbytes) AS sumbytes\nFROM (\n    SELECT\n        $timeSeries AS t,\n        sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\n    FROM $table\n    WHERE $timeFilter and ((etype = 0x800) and (equals($srcip, 'All') or (IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))) = $srcip)))\n    GROUP BY t\n\n    UNION ALL\n\n    SELECT\n        toInt64(intDiv($from+number*$interval, $interval)*$interval*1000) AS t,\n        0 AS sumbytes\n    FROM numbers(intDiv($to-$from, $interval))\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    t,\n    sum(sumbytes) AS sumbytes\nFROM (\n    SELECT\n        (intDiv(toFloat64(time_flow_start_ns) * 1000, (300 * 1000)) * (300 * 1000)) AS t,\n        sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\n    FROM default.flows_raw\n    WHERE date >= toDate(1719800042) AND date <= toDate(1719886442) AND time_flow_start_ns >= toDateTime64(1719800042, 3) AND time_flow_start_ns <= toDateTime64(1719886442, 3) and ((etype = 0x800) and (equals('0.0.0.0', 'All') or (IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))) = '0.0.0.0')))\n    GROUP BY t\n\n    UNION ALL\n\n    SELECT\n        toInt64(intDiv(1719800042+number*300, 300)*300*1000) AS t,\n        0 AS sumbytes\n    FROM numbers(intDiv(1719886442-1719800042, 300))\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "bytes" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top source and destination IPs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY srcip, dstip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE time_flow_start_ns >= toDateTime64(1719296079, 3) AND time_flow_start_ns <= toDateTime64(1719296379, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY srcip, dstip\nORDER BY sumbytes DESC",
     "rawSql": "SELECT src_ip, count(*), sum(bytes) AS sumBytes FROM flows GROUP BY src_ip",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Top source and destination IPs",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY srcip, dstip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE time_flow_start_ns >= toDateTime64(1719296079, 3) AND time_flow_start_ns <= toDateTime64(1719296379, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY srcip, dstip\nORDER BY sumbytes DESC",
     "rawSql": "SELECT src_ip, count(*), sum(bytes) AS sumBytes FROM flows GROUP BY src_ip",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Top source IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY srcip\nORDER BY sumbytes DESC",
     "query": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY srcip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719473440) AND date <= toDate(1719559840) AND time_flow_start_ns >= toDateTime64(1719473440, 3) AND time_flow_start_ns <= toDateTime64(1719559840, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY srcip\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top source IPs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY srcip\nORDER BY sumbytes DESC",
     "query": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY srcip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719296090) AND date <= toDate(1719296390) AND time_flow_start_ns >= toDateTime64(1719296090, 3) AND time_flow_start_ns <= toDateTime64(1719296390, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY srcip\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top destination IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY dstip\nORDER BY sumbytes DESC",
     "query": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY dstip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719296117) AND date <= toDate(1719296417) AND time_flow_start_ns >= toDateTime64(1719296117, 3) AND time_flow_start_ns <= toDateTime64(1719296417, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY dstip\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top destination IPs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY dstip\nORDER BY sumbytes DESC",
     "query": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY dstip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719296117) AND date <= toDate(1719296417) AND time_flow_start_ns >= toDateTime64(1719296117, 3) AND time_flow_start_ns <= toDateTime64(1719296417, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY dstip\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top source ports",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(src_port) as port,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY port\nORDER BY sumbytes DESC",
     "query": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(src_port) as port,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY port\nORDER BY sumbytes DESC",
     "rawQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(src_port) as port,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719296099) AND date <= toDate(1719296399) AND time_flow_start_ns >= toDateTime64(1719296099, 3) AND time_flow_start_ns <= toDateTime64(1719296399, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY port\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top source ports",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(src_port) as port,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY port\nORDER BY sumbytes DESC",
     "query": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(src_port) as port,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY port\nORDER BY sumbytes DESC",
     "rawQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(src_port) as port,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719296099) AND date <= toDate(1719296399) AND time_flow_start_ns >= toDateTime64(1719296099, 3) AND time_flow_start_ns <= toDateTime64(1719296399, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY port\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top destination ports",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(dst_port) as port,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY port\nORDER BY sumbytes DESC",
     "query": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(dst_port) as port,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY port\nORDER BY sumbytes DESC",
     "rawQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(dst_port) as port,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719296126) AND date <= toDate(1719296426) AND time_flow_start_ns >= toDateTime64(1719296126, 3) AND time_flow_start_ns <= toDateTime64(1719296426, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY port\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top destination ports",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(dst_port) as port,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY port\nORDER BY sumbytes DESC",
     "query": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(dst_port) as port,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY port\nORDER BY sumbytes DESC",
     "rawQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(dst_port) as port,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719296126) AND date <= toDate(1719296426) AND time_flow_start_ns >= toDateTime64(1719296126, 3) AND time_flow_start_ns <= toDateTime64(1719296426, 3) and ((etype = 0x800) or (etype = 0x86dd))\nGROUP BY port\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top source IPs and inner source IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY srcip\nORDER BY sumbytes DESC",
     "query": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    IPv6NumToString(in_src_addr) as in_srcip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd)) and (hex(in_src_addr) != '00000000000000000000000000000000')\nGROUP BY srcip, in_srcip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    IPv6NumToString(in_src_addr) as in_srcip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719278452) AND date <= toDate(1719364852) AND time_flow_start_ns >= toDateTime64(1719278452, 3) AND time_flow_start_ns <= toDateTime64(1719364852, 3) and ((etype = 0x800) or (etype = 0x86dd)) and (hex(in_src_addr) != '00000000000000000000000000000000')\nGROUP BY srcip, in_srcip\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top source IPs and inner source IPs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY srcip\nORDER BY sumbytes DESC",
     "query": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    IPv6NumToString(in_src_addr) as in_srcip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM $table\nWHERE $timeFilter and ((etype = 0x800) or (etype = 0x86dd)) and (hex(in_src_addr) != '00000000000000000000000000000000')\nGROUP BY srcip, in_srcip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(src_addr), 13,4))), IPv6NumToString(src_addr)) as srcip,\n    IPv6NumToString(in_src_addr) as in_srcip,\n    sum(if(sampling_rate =0, bytes, bytes * sampling_rate)) as sumbytes\nFROM default.flows_raw\nWHERE date >= toDate(1719278452) AND date <= toDate(1719364852) AND time_flow_start_ns >= toDateTime64(1719278452, 3) AND time_flow_start_ns <= toDateTime64(1719364852, 3) and ((etype = 0x800) or (etype = 0x86dd)) and (hex(in_src_addr) != '00000000000000000000000000000000')\nGROUP BY srcip, in_srcip\nORDER BY sumbytes DESC",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  }
 ]
}