{{- if .Values.cleanup.enabled }}
{{- if (index .Values "altinity-clickhouse-operator" "enabled") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "3"
    # use (before-hook-creation) for debug
    #    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: {{ .Release.Name }}-cleanup
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-cleanup
      labels:
        app: {{ .Release.Name }}-cleanup
    spec:
      containers:
        - name: kubectl
          image: "{{ .Values.hyperkubeImage.repository }}:{{ .Values.hyperkubeImage.tag }}"
          imagePullPolicy: "{{ .Values.hyperkubeImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - >
                  kubectl -n {{.Release.Namespace}} patch clickhouseinstallations.clickhouse.altinity.com/{{.Release.Name}}-{{index .Values "clickhouse-instance" "name-suffix"}} -p '{"metadata":{"finalizers":[]}}' --type=merge
      restartPolicy: Never
  backoffLimit: 2
{{- end }}
{{- end }}
