kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chi-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    # post-delete hook needs this resource to execute command
    "helm.sh/resource-policy": keep
    "helm.sh/hook-weight": "-5"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chi-patch
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    # post-delete hook needs this resource to execute command
    "helm.sh/resource-policy": keep
    "helm.sh/hook-weight": "-4"
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: chi-admin
  apiGroup: rbac.authorization.k8s.io

