apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "udprepl.fullname" . }}
  labels:
    {{- include "udprepl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "udprepl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "udprepl.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "udprepl.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - /bin/sh
            - '-c'
            - |
              /bin/sh <<'EOF'
            {{- if .Values.cmdstr }}
              {{ tpl (.Values.cmdstr) . | nindent 14 }}
            {{- else }}
              /udp-replicator \
              {{- range $key, $value := .Values.forward }}
              --forward {{ tpl ( $value.target ) $ }} \
              {{- end }}
              --listen-port={{ .Values.service.port }}
            {{- end }}
              EOF

          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
